---
- name: Add the official istio helm repository
  shell: "helm --kube-context {{ cluster_name }} repo add istio.io {{ istio_chart_rep_url }}"

- name: Create istio namespace
  shell: kubectl --context "{{ cluster_name }}" get ns "{{ istio_namespace }}" || kubectl --context "{{ cluster_name }}" create ns "{{ istio_namespace }}"

- name: Install Istio Custom Resource Definitions
  include_role:
    name: deploy_helm_chart
  vars:
    release_name: istio-init
    namespace: "{{ istio_namespace }}"
    chart_name: istio.io/istio-init
    chart_version: "{{ istio_version }}"

- name: "Confirm that istio CRDs has been installed"
  shell: |
    kubectl --context {{ cluster_name }} get --all-namespaces gateways.networking.istio.io && \
    kubectl --context {{ cluster_name }} get --all-namespaces envoyfilters.networking.istio.io && \
    kubectl --context {{ cluster_name }} get --all-namespaces policies.authentication.istio.io && \
    kubectl --context {{ cluster_name }} get --all-namespaces destinationrules.networking.istio.io && \
    kubectl --context {{ cluster_name }} get --all-namespaces virtualservices.networking.istio.io && \
    kubectl --context {{ cluster_name }} get --all-namespaces envoyfilters.networking.istio.io && \
    kubectl --context {{ cluster_name }} get --all-namespaces attributemanifests.config.istio.io && \
    kubectl --context {{ cluster_name }} get --all-namespaces handlers.config.istio.io && \
    kubectl --context {{ cluster_name }} get --all-namespaces meshpolicies.authentication.istio.io
  register: crd_check
  until: crd_check.rc == 0
  retries: 10
  delay: 5
  ignore_errors: false

- name: Remove tls secret from the istio namespace
  shell: kubectl --context {{ cluster_name }} -n {{ istio_namespace }} delete secret {{ base_domain }}-tls --ignore-not-found

- name: Copy TLS secret to the istio namespace
  shell: "kubectl --context {{ cluster_name }} get secret {{ source_secret_name }} -o json --namespace kube-system | jq '.metadata.namespace = \"{{ istio_namespace }}\"' | jq '.metadata.name = \"{{ base_domain }}-tls\"' | kubectl apply -n {{ istio_namespace }} --context {{ cluster_name }} -f -"

- name: Create Istio helm values file
  template:
    src: istio-values.yml.j2
    dest: "{{ istio_values_file }}"
    mode: 0644

- name: Install Istio
  include_role:
    name: deploy_helm_chart
  vars:
    release_name: istio
    namespace: "{{ istio_namespace }}"
    values_file: "{{ istio_values_file }}"
    chart_name: istio.io/istio
    chart_version: "{{ istio_version }}"
