---

- name: Generate cookie secret
  set_fact:
    cookie_secret: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters') | b64encode }}"

- name: Create Dex oauth2-proxy configuration (values) file
  template:
    src: oauth2-proxy.yml.j2
    dest: "{{ oauth_proxy_values_file }}"
    mode: 0644
  when: dex.enabled

- name: Install oauth2-proxy
  include_role:
    name: deploy_helm_chart
  vars:
    release_name: dex-oauth2-proxy
    namespace: "kube-system"
    values_file: "{{ oauth_proxy_values_file }}"
    chart_name: stable/oauth2-proxy
    chart_version: "{{ oauth_proxy_chart_version }}"
  when: dex.enabled