---
dashboard:
  version: "1.10.1"
  insecure: true
source_secret_name: "{{ base_domain }}-tls"
monitoring_values_file: "{{ tmp_dir }}/monitoring.{{ cluster_name }}.yml"
# Cluster logs
kube_fluentd:
  kube_s3_bucket_name: epm-legion-data-dev-logs
  kube_s3_bucket_region: us-east-2
  # kube_s3_bucket_prefix: cluster_logs
  system_s3_bucket_name: epm-legion-data-dev-logs
  system_s3_bucket_region: us-east-2
  # system_s3_bucket_prefix: cluster_logs
  services_s3_bucket_name: epm-legion-data-dev-logs
  services_s3_bucket_region: us-east-2
  # services_s3_bucket_prefix: cluster_logs

oauth_proxy_values_file: "{{ tmp_dir }}/oauth2-proxy.{{ cluster_name }}.yml"
oauth_proxy_chart_version: "0.12.2"

istio_version: "1.2.2"
istio_cni_version: "0.1.0"
istio_chart_rep_url: https://storage.googleapis.com/istio-release/releases/{{ istio_version }}/charts
istio_namespace: istio-system
istio_values_file: "{{ tmp_dir }}/istio.{{ cluster_name }}.yml"

knative_namespace: "knative-serving"