---

- name: Upload TLS certificate to S3
  aws_s3:
    bucket: "{{ secrets_bucket }}"
    object: "{{ remote_tls_location }}/{{ item }}"
    src: "{{ tls_new_cert_dir }}/{{ item }}"
    mode: put
    metadata: 'Content-Type=text/plain'
  loop:
    - "{{ tls_fullchain_file_name }}"
    - "{{ tls_key_file_name }}"
  
