---
###########################
# Setup Kubernetes Cluster
###########################

# NOTICE:
# You Must specify profile name as an extra var (--extra-vars "cluster_name=XXXX") 

- hosts: localhost
  connection: local
  gather_facts: True

  vars_files:
    - vars/gcp-common.yaml

  roles:
    - certificates
