---

- name: Get {{ release_name }} chart status
  shell: helm --kube-context {{ cluster_name }} ls --all '^{{ release_name }}$'
  register: chart_status

- include: delete_chart.yaml
  when: chart_status.stdout_lines|length > 1

- include: install_chart.yaml